### ISSUE TITLE
Java JSON <--> POJO classes, where?

### ISSUE THREAD

**Issue by pablopareja** [bio4j/bio4j-examples#12]
Hey @eparejatobes @laughedelic 

So far I'm coding here the POJO classes I need to export Bio4j entities/data to JSON.
However, since a few days ago I need to customize that a bit from other projects and I was wondering if it would be a good idea to write all these POJO classes as a separate repository?
WDYT? :question: 

Here are the classes aforementioned: 
https://github.com/bio4j/bio4j-examples/tree/master/src/main/java/com/bio4j/examples/json/model

**Comment by laughedelic** [comment]
plain old Java object (POJO):

> "We wondered why people were so against using regular objects in their systems and concluded that it was because simple objects lacked a fancy name. So we gave them one, and it's caught on very nicely."

LOL :stuck_out_tongue_closed_eyes:

What do you need those POJOs for?

**Comment by pablopareja** [comment]
To serialize/deserialize from JSON using GSON

**Comment by eparejatobes** [comment]
I think it would be better to put those classes somewhere else. They are more about JSON serialization in Java than Bio4j.

**Comment by pablopareja** [comment]
Ok but where?

**Comment by pablopareja** [comment]
I was thinking of creating a new repository: **bio4j-json** 
WDYT?

**Comment by eparejatobes** [comment]
fine for me :+1:

**Comment by pablopareja** [comment]
cool I'm going to create it then
closing...
